Allow product-specific postbuild scripts.

diff --git a/fzmake/scripts/nightlygen b/fzmake/scripts/nightlygen
--- a/fzmake/scripts/nightlygen
+++ b/fzmake/scripts/nightlygen
@@ -10,6 +10,7 @@ CONFDIR=
 
 STRIP=
 UPDATE=true
+SIGN=true
 
 while [ -n "$1" ]; do
   case $1 in
@@ -50,6 +51,22 @@ while [ -n "$1" ]; do
     ;;
     --update=*)
       echo "Invalid argument to --update"
+      exit 1
+    ;;
+    --nosign)
+      SIGN=false
+      shift 1
+    ;;
+    --sign=false)
+      SIGN=false
+      shift 1
+    ;;
+    --sign=true)
+      SIGN=true
+      shift 1
+    ;;
+    --sign=*)
+      echo "Invalid argument to --sign"
       exit 1
     ;;
     *)
@@ -105,6 +122,7 @@ init || exit 1
 echo "#! /bin/sh" > "$PREFIX/clientscripts/parameters"
 chmod +x "$PREFIX/clientscripts/parameters"
 echo "export STRIP=$STRIP" >> "$PREFIX/clientscripts/parameters"
+echo "export SIGN=$SIGN" >> "$PREFIX/clientscripts/parameters"
 
 clean_files()
 {
@@ -164,6 +182,7 @@ applypatches()
 }
 
 export DATE=`date "+%Y-%m-%d"`
+export SHORTDATE=`date "+%Y%m%d"`
 export OUTPUTDIR="$WWWDIR/$DATE"
 export LOG="$OUTPUTDIR/build.log"
 
@@ -184,9 +203,10 @@ START=`date "+%Y-%m-%d %H:%M:%S"`
 logprint "Build started: $START\n"
 resetHosts || buildfailure || exit 1
 while getHost; do
-  for i in $TARGETS; do
-    mkdir -p "$OUTPUTDIR/$i"
-    touch "$OUTPUTDIR/$i/pending"
+  for TARGET in $TARGETS; do
+    FTARGET="${TARGET##*/}"
+    mkdir -p "$OUTPUTDIR/$FTARGET"
+    touch "$OUTPUTDIR/$FTARGET/pending"
   done
 done
 resetHosts
